<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [5]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.5.4)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.3.3)

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [7]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [9]:
# Write your code here
df.dtypes

ResponseId               int64
MainBranch                 str
Age                        str
Employment                 str
RemoteWork                 str
                        ...
JobSatPoints_11        float64
SurveyLength               str
SurveyEase                 str
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

In [11]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=114)

In [18]:
missing_value = df.isnull().sum()
print(missing_value)

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [13]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [22]:
# Write your code here
print(df['Country'].unique())

<ArrowStringArray>
[                            'United States of America',
 'United Kingdom of Great Britain and Northern Ireland',
                                               'Canada',
                                               'Norway',
                                           'Uzbekistan',
                                               'Serbia',
                                               'Poland',
                                          'Philippines',
                                             'Bulgaria',
                                          'Switzerland',
 ...
                                'Saint Kitts and Nevis',
                                               'Monaco',
                   'Micronesia, Federated States of...',
                                                'Haiti',
                                                    nan,
                                                'Nauru',
                                              'Liberia',
                                                 'Chad',
                                             'Djibouti',
                                      'Solomon Islands']
Length: 186, dtype: str

In [23]:
print(df['EdLevel'].unique())

<ArrowStringArray>
[                                                         'Primary/elementary school',
                                       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
                                    'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
                             'Some college/university study without earning a degree',
 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
                                     'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
                                                'Associate degree (A.A., A.S., etc.)',
                                                                     'Something else',
                                                                                  nan]
Length: 9, dtype: str

In [26]:
df['Country'] = df['Country'].str.strip().str.title()
df['EdLevel'] = df['EdLevel'].str.strip()

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [37]:
## Write your code here
# Create a dictionary to simplify and standardize education levels
# 1. Fill the NaN value using the most common answer (the mode)
most_common_ed = df['EdLevel'].mode()[0]

# 2. Use a dictionary with fillna() and inplace=True as requested
df.fillna(value={'EdLevel': most_common_ed}, inplace=True)

# 2. Standardize the 9 strings into clean concise format
ed_mapping = {
    'Primary/elementary school': 'Primary school',
    'Bachelor’s degree (B.A., B.S., B.Eng., etc.)': 'Bachelor Degree',
    'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)': 'Master Degree',
    'Some college/university study without earning a degree': 'Some College',
    'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)': 'High School',
    'Professional degree (JD, MD, Ph.D, Ed.D, etc.)': 'Professional Degree',
    'Associate degree (A.A., A.S., etc.)': 'Associate Degree',
    'Something else': 'Other'
}

# 4. Map the messy names to the clean names
df['EdLevel'].replace(ed_mapping, inplace=True)

# 3. Verify that the NaN are gone and values are clean
print(df['EdLevel'].value_counts(dropna=False))

EdLevel
Bachelor Degree     29595
Master Degree       15557
Some College         7651
High School          5793
Ph. D                2970
Associate Degree     1793
Primary school       1146
Certificate           932
Name: count, dtype: int64

/tmp/ipykernel_787/2566537093.py:22: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['EdLevel'].replace(ed_mapping, inplace=True)

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [42]:
## Write your code here
import pandas as pd

employment_dummies = pd.get_dummies(df['Employment'], prefix='Employment')

df = pd.concat([df, employment_dummies], axis=1)

print("--- New One-Hot Encoded Columns ---")
print([col for col in df.columns if col.startswith('Employment')])

print("\n--- Data Preview ---")
print(df[[col for col in df.columns if col.startswith('Employment')]].head())

--- New One-Hot Encoded Columns ---

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [46]:
## Write your code here
missing_counts = df.isnull().sum()

top_missing_cols = missing_counts.sort_values(ascending=False).head(5)

print("--- Top 5 Columns with the Hidden Number of Missing Values ---")
print(top_missing_cols)

--- Top 5 Columns with the Hidden Number of Missing Values ---
AINextMuch less integrated    64289
AINextLess integrated         63082
AINextNo change               52939
AINextMuch more integrated    51999
EmbeddedAdmired               48704
dtype: int64

In [51]:
ai_mode = df['AINext'].mode()[0]
df['AINext'].fillna(ai_mode, inplace=True)

ai_mapping = {
    'AI next much': 'Much More AI',
    'AI next less':  'Less AI',
    'AI next no': 'No AI',
    'AI next much more': 'Much More AI',
    'embedded admire': 'Embedded AI / Admired'
}

df['AINext'].replace(ai_mapping, inplace=True)

print(df['AINext'].value_counts(dropna=False))

KeyError: 'AINext'

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [ ]:
## Write your code here

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [ ]:
## Write your code here

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [ ]:
## Write your code here

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [ ]:
## Write your code here

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [ ]:
## Write your code here

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.